refactor: image 도메인 헥사고날 아키텍처 적용
depromeet/15th-team2-BE pull request #110
Opened 2024-07-26 15:58 UTC by penrose15

## 🌱 관련 이슈

- close #107 

## 📌 작업 내용 및 특이사항
- Image 도메인 헥사고날 아키텍처 적용하였습니다.

- s3 로직을 module-infrastructure에 포함시키고 module-domain의 s3ManagePort를 통해 의존성을 분리하였습니다. 
- module-infrastructure 아래에 object-storage 모듈을 추가하여 s3 관련 로직을 추가하였습니다. (object storage뜻이 데이터를 오브젝트로 관리하는 스토리지라는 뜻이더군요) 더 나은 패키지 명을 추천받습니다.  
-혹시 잘못 구현한 부분이 있다면 피드백 부탁드립니다.

## 📝 참고사항
-

2024-07-26 16:55 UTC, its-sky requested changes
너무 좋네요 수고하셨습니다 ~

2024-07-26 16:55 UTC, its-sky commented on module-domain/src/main/java/com/depromeet/image/port/in/ImageUploadUseCase.java
> +    List<ImagePresignedUrlCommand> getPresignedUrlAndSaveImages(List<String> originImageNames);
Command와 Query는 presentation 모듈에서 domain 모듈로 넘기는 dto를 담을 때 사용합니다! 일반적으로 Command는 (Create, Update, Delete), Query(Get)으로 사용합니다. 그래서 제 생각에는 ImagePresignedUrlCommand의 네이밍이 아니라 ImagePresignedUrlVo 정도로 정리해도 좋을거 같습니다!

2024-07-26 16:55 UTC, its-sky commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
> +    }
이건 toModel을 할 때 ImageEntity의 MemoryEntity를 꺼내므로 fetch join을 통해서 쿼리 최적화하면 좋을거 같습니다~

2024-07-26 16:55 UTC, its-sky commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
> +        imageJpaRepository.deleteAllByMemoryId(memoryId);
deleteAllInBatch로 쿼리 최적화하면 좋을거 같습니다~

2024-07-26 16:55 UTC, its-sky commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
> +        imageJpaRepository.deleteAllByMemoryId(memoryId);
전반적으로 Image 조회는 Memory를 포함하도록 fetch join 하면 좋을거 같고 삭제 쿼리는 배치 삭제로 처리하면 좋을거 같아요~

2024-07-26 16:55 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
> +    private final ImageDeleteUseCase imageDeleteUseCase;
길이순 정렬 가능한가요? ㅋㅋ

2024-07-27 03:48 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
> +    private final ImageDeleteUseCase imageDeleteUseCase;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-07-27 07:30 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
> +        imageJpaRepository.deleteAllByMemoryId(memoryId);
> deleteAllInBatch로 쿼리 최적화하면 좋을거 같습니다~

이 부분에 대해서 deleteAllByMemoryIdInBatch 적용시 오류가 발생하여 

```
@Modifying
    @Query("delete from ImageEntity i where i.memory.id = :memoryId")
    void deleteAllByMemoryId(@Param("memoryId") Long memoryId);
```
jpql 쿼리를 활용하여 해결하였습니다

2024-07-27 07:58 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageRepository.java
> +        imageJpaRepository.deleteAllByMemoryId(memoryId);
나머지 부분도 fetchJoin 붙였습니다~

2024-07-27 08:11 UTC, its-sky approved these changes
수고하셨습니다~

2024-07-27 08:11 UTC, its-sky commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/image/repository/ImageJpaRepository.java
> +    void deleteAllByMemoryId(@Param("memoryId") Long memoryId);
이거 이렇게 쿼리 직접 쓰실 필요는 없고 JpaRepository의 deleteAllInBatch라는 메소드가 있어요! 일단 같은 역할하면 상관없긴 합니다

2024-07-27 08:11 UTC, its-sky commented on module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MemberFixture.java
> +    public static Member memberFixture() {
Fixture는 객체를 생성하는 일종의 팩토리인데 약간 메소드명이 어색한거 같아요

2024-07-27 08:11 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
> +    private final MemoryService memoryService;
MemoryService는 왜 있는지 알 수 있을까요?

2024-07-27 08:43 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/facade/ImageFacade.java
> +    private final MemoryService memoryService;
아 아직 memory 부분은 헥사고날이 적용이 안되어서 임시로 해두었습니다.  추후 변경되면 적용하겠습니다

2024-07-27 08:44 UTC, penrose15 commented on module-infrastructure/persistence-database/src/test/java/com/depromeet/fixture/member/MemberFixture.java
> +    public static Member memberFixture() {
아 찾아보니 그러네요 수정했습니다

2024-07-27 09:10 UTC, merged