feat: 수영 기록 상세 수정 구현
depromeet/15th-team2-BE pull request #72
Opened 2024-07-18 20:05 UTC by ywonchae1

## 🌱 관련 이슈

- close #71

## 📌 작업 내용 및 특이사항
- 수영 기록 상세 수정을 구현하였습니다.
- Memory와 Stroke를 분리하고 싶었는데, 연관성이 깊어서 분리하기가 어려웠습니다.🥵
- Controller 단에서 Stroke를 업데이트 한 뒤 Memory와 MemoryDetail을 수정합니다.
- 이 과정에서 Stroke 업데이트가 완료되었음에도 findById로 Memory를 불러왔을 때 업데이트된 Stroke 정보가 반영되지 않았습니다. (DB에는 반영이 됨)
- 그래서 업데이트된 Stroke 정보를 가지고 Memory 업데이트를 진행하였습니다.
- Controller 단에서 이와 같이 분리된 경우 특정 부분에서 예외가 발생하여 실패하였을 때 이전 작업이 commit 되었습니다. (!)

## 📝 참고사항
- Stroke와 같은 문제로 인해 이미지 수정 시 코드 변경이 필요할 것 같습니다.
- 지금 구현된 방식에 대한 의견이 궁금합니다 !!
<img width="855" alt="Screenshot 2024-07-19 at 04 21 27" src="https://github.com/user-attachments/assets/237e0959-efde-4ee8-8644-5566a99c1a31">
- **요청 예시**
```
{
  "poolId": null,
  "item": "오리발, 킥판",
  "heartRate": 129,
  "pace": "05:00:00",
  "kcal": 300,
  "recordAt": "2024-07-18",
  "startTime": "11:00:00",
  "endTime": "11:50:00",
  "lane": 25,
  "diary": "나는 짱이야!! 내가 정말 멋져!! 히ㅣ히힛",
  "strokes": [
    {
      "id": 1,
      "name": "자유형",
      "laps": 3,
      "meter": null
    },
    {
      "id": null,
      "name": "접영",
      "laps": 4,
      "meter": null
    }
  ]
}
```
- **응답 예시**
```
{
    "status": 200,
    "code": "MEMORY_3",
    "message": "수영 기록 수정에 성공하였습니다",
    "data": {
        "id": 1,
        "member": {
            "goal": null,
            "name": "양원채"
        },
        "pool": null,
        "memoryDetail": {
            "id": 1,
            "item": "오리발, 킥판",
            "heartRate": 129,
            "pace": "05:00:00",
            "kcal": 300
        },
        "strokes": [
            {
                "id": 1,
                "memory": null,
                "name": "자유형",
                "laps": 3,
                "meter": 75
            },
            {
                "id": 16,
                "memory": null,
                "name": "접영",
                "laps": 4,
                "meter": 100
            }
        ],
        "images": [],
        "recordAt": "2024-07-18",
        "startTime": "11:00:00",
        "endTime": "11:50:00",
        "duration": "00:50:00",
        "lane": 25,
        "totalLap": 7,
        "totalMeter": 175,
        "diary": "나는 짱이야!! 내가 정말 멋져!! 히ㅣ히힛"
    }
}
```

- **영법 바퀴 수를 미터로 바꾸어도 잘 동작해요**
<img width="848" alt="Screenshot 2024-07-19 at 05 04 10" src="https://github.com/user-attachments/assets/9b8692fe-a038-4aa9-b3cc-c61fc994fb11">

- **작성자가 아닌 경우**
<img width="864" alt="Screenshot 2024-07-19 at 05 00 37" src="https://github.com/user-attachments/assets/2a1e4bae-197c-4a24-9611-1a566d5db38e">

- **입력 값 검증에 실패**
<img width="856" alt="Screenshot 2024-07-19 at 05 02 32" src="https://github.com/user-attachments/assets/c7bfea3f-0d2d-4542-a471-8c5b7c5c2027">

2024-07-19 03:51 UTC, its-sky requested changes
굿 수고하셨어용~ 코멘트 확인 부탁드려요!

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
> +            updatedImageNames.add(imageName); // 이게 if문 밑으로 내려가야 하지 않을까요?
인정따리 입니다~

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryService.java
>  }
이제 Service에서는 도메인 클래스를 반환하고 컨트롤러에서 Dto로 매핑하는 로직으로 바꾸신거겠죠???

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        // memory 수정
주석 앞에 대문자 맞춰주는거 가능? 일관성 강박증이라 ㅋㅋ

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        return memoryRepository.save(memory);
여긴 왜 save를 했을까요? 제가 봤을때는 JPA dirty checking으로 변경사항 자동 커밋 될거 같은데.!!

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
> +            @PathVariable("memoryId") Long memoryId,
여기 파라미터로 `@CurrentMember Long id` 하면 현재 로그인한 멤버 아이디 자동으로 주입해줌~!
`validateMemoryMemberMismatch(Memory memory)` 메소드에서 `authorizationUtil` 쓰고 있길래 주입 받아서 파라미터로 넘겨주면 될거 같슴니다!

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +        List<Stroke> beforeStrokes = memory.getStrokes();
혹시 여기 쿼리 몇방나가는지 알수 있나요?

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +    }
여긴 충분히 코드로 다 설명가능한거 같은데 주석 삭제해도 좋을거 같아요~!

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
>          memoryDetailRepository.save(updateMemoryDetail);
기존 DB에 저장되어 있는 엔티티를 변경할 때 이렇게 save 안해줘도 자동으로 변경감지해서 커밋해줘요~

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +            updateMemoryDetail = memory.getMemoryDetail().update(updateMemoryDetail);
여긴 기존에 존재하는 memoryDetail의 필드를 바꾸지 않고 빌더로 새 객체를 만드는 이유가 있을까요? 기존 필드만 변경하면 dirty checking을 이용할 수 있을거 같아서 질문드립니다!

2024-07-19 03:51 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
>          memoryDetailRepository.save(updateMemoryDetail);
그래서 기존 memoryDetail이 있을때는 필드를 업데이트하고 early return을 해서 save 메소드를 안만나도록 해도 될거 같아요~

2024-07-19 04:08 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
> +            updatedImageNames.add(imageName); // 이게 if문 밑으로 내려가야 하지 않을까요?
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-07-19 04:08 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryService.java
>  }
넵 맞습니닷

2024-07-19 04:09 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        // memory 수정
헐 !!!! 이런 치명적인 실수를 완전 감사해용

2024-07-19 04:10 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        return memoryRepository.save(memory);
근데 저희가 영속성 객체랑 도메인 객체를 분리한 상태라 Memory가 Domain객체라 JPA dirty checking이 안 될 거라고 생각했어요..
MemoryEntity일 때는 JPA dirty checking이 되는 게 아닌지!?
Memory에도 JPA dirty checking이 적용되나요???

2024-07-19 04:11 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
> +            @PathVariable("memoryId") Long memoryId,
와우 전에 말했던 게 그거구나 고마오!!!!

2024-07-19 04:11 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +        List<Stroke> beforeStrokes = memory.getStrokes();
앗........... 확인 해볼게요..!!!

2024-07-19 04:11 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +    }
넵 !!

2024-07-19 04:16 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        return memoryRepository.save(memory);
repository에 id랑 변경포인트를 넘기고 해당 id의 엔티티를 조회한다음 변경포인트 필드만 업데이트하면 되지 않을까용?

2024-07-19 04:19 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        return memoryRepository.save(memory);
그러면 update 로직이 repository로 넘어가는 거네요!
그렇게 수정해 보겠습니당

2024-07-19 04:20 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
>          memoryDetailRepository.save(updateMemoryDetail);
요것도 update 로직을 repository로 넘겨서 처리하겠습니다!!!

2024-07-19 04:21 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
>          memoryDetailRepository.save(updateMemoryDetail);
근데 만약 지금 로직으로 하게 되면 기존 객체는 어떻게 되는건가요??

2024-07-19 04:25 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +            updateMemoryDetail = memory.getMemoryDetail().update(updateMemoryDetail);
위에서 논의한 대로 도메인 객체라서 dirty checking이 불가능하다고 생각을 했구,
만약 update 로직을 repository로 넘기는 걸로 변경하게 되면 id랑 업데이트 데이터를 가진 updateMemoryDetail 객체를 만들어서 넘겨야 하지 않나요 ??

2024-07-19 04:26 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
> +    @Schema(description = "수영장 정보 Id", example = "null")
어떤건 record 쓰고 어떤건 class를 쓰는 이유가 있을까요? 하나로 통일하는게 좋을 듯 합니다

2024-07-19 04:26 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/service/MemoryServiceImpl.java
> +        // memory 수정
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-07-19 05:08 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
> +            updatedImageNames.add(imageName); // 이게 if문 밑으로 내려가야 하지 않을까요?
저거 밑으로 내리면 나중에 delete에서 삭제 대상 비교할 때 필터링 제대로 안됨

2024-07-19 10:08 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
> +            updatedImageNames.add(imageName); // 이게 if문 밑으로 내려가야 하지 않을까요?
그럼 이부분은 그냥 MultipartFile들을 통해 이미지 이름인 String을 추출하는 과정인가요??
약간 이해가 잘 안 되긴 하지만 .. 일단 넘어가겠습니다!!

2024-07-19 11:11 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
> +    @Schema(description = "수영장 정보 Id", example = "null")
테스트코드 짤 때 Builder를 사용하려면 class여야 해서 class로 사용했습니다!

2024-07-19 11:15 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
> +            @PathVariable("memoryId") Long memoryId,
제 버전에서는 애노테이션 작성이 안 되네요.!!!

2024-07-19 11:26 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +        List<Stroke> beforeStrokes = memory.getStrokes();
```
Hibernate: 
    select
        me1_0.memory_id,
        me1_0.diary,
        me1_0.end_time,
        me1_0.lane,
        me1_0.member_id,
        me1_0.memory_detail_id,
        me1_0.pool_id,
        me1_0.record_at,
        me1_0.start_time 
    from
        memory_entity me1_0 
    where
        me1_0.memory_id=?
2024-07-19T20:24:39.402+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2024-07-19T20:24:39.402+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(2055771373<open>)]
2024-07-19T20:24:39.403+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
Hibernate: 
    select
        me1_0.member_id,
        me1_0.email,
        me1_0.name,
        me1_0.refresh_token,
        me1_0.role 
    from
        member_entity me1_0 
    where
        me1_0.member_id=?
Hibernate: 
    select
        mde1_0.memory_detail_id,
        mde1_0.heart_rate,
        mde1_0.item,
        mde1_0.kcal,
        mde1_0.pace 
    from
        memory_detail_entity mde1_0 
    where
        mde1_0.memory_detail_id=?
Hibernate: 
    select
        s1_0.memory_id,
        s1_0.stroke_id,
        s1_0.laps,
        s1_0.meter,
        s1_0.name 
    from
        stroke_entity s1_0 
    where
        s1_0.memory_id=?
Hibernate: 
    select
        i1_0.memory_id,
        i1_0.image_id,
        i1_0.image_name,
        i1_0.image_url,
        i1_0.origin_image_name 
    from
        image_entity i1_0 
    where
        i1_0.memory_id=?
2024-07-19T20:24:39.418+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(2055771373<open>)] for JPA transaction
2024-07-19T20:24:39.418+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [org.springframework.data.jpa.repository.support.SimpleJpaRepository.save]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2024-07-19T20:24:39.418+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@603c81dc]
2024-07-19T20:24:39.423+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2024-07-19T20:24:39.423+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(2055771373<open>)]
2024-07-19T20:24:39.428+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
2024-07-19T20:24:39.429+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Found thread-bound EntityManager [SessionImpl(2055771373<open>)] for JPA transaction
2024-07-19T20:24:39.429+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Creating new transaction with name [org.springframework.data.jpa.repository.support.SimpleJpaRepository.save]: PROPAGATION_REQUIRED,ISOLATION_DEFAULT
2024-07-19T20:24:39.429+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Exposing JPA transaction as JDBC [org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle@26c46413]
2024-07-19T20:24:39.429+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Initiating transaction commit
2024-07-19T20:24:39.429+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Committing JPA transaction on EntityManager [SessionImpl(2055771373<open>)]
Hibernate: 
    update
        stroke_entity 
    set
        laps=?,
        memory_id=?,
        meter=?,
        name=? 
    where
        stroke_id=?
2024-07-19T20:24:39.443+09:00 DEBUG 3886 --- [nio-8080-exec-7] o.s.orm.jpa.JpaTransactionManager        : Not closing pre-bound JPA EntityManager after transaction
Hibernate: 
    select
        se1_0.stroke_id,
        se1_0.laps,
        se1_0.memory_id,
        se1_0.meter,
        se1_0.name 
    from
        stroke_entity se1_0 
    where
        se1_0.memory_id=?
```

로그는 이렇게 찍히고, 7번 날아가는 것 같습니다!

2024-07-19 11:33 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/dto/request/MemoryUpdateRequest.java
> +    @Schema(description = "수영장 정보 Id", example = "null")
record에서 compact constructor 생성하고 위에 @Builder 추가해도 안 되던가요

2024-07-19 11:35 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/image/service/ImageUpdateServiceImpl.java
> +            updatedImageNames.add(imageName); // 이게 if문 밑으로 내려가야 하지 않을까요?
음... 두 번 반복하는거 한번으로 줄여보려고 한건데 그냥 분리하는 게 낫겠네요 다음 PR 에 반영하겠습니다.

2024-07-19 16:49 UTC, its-sky approved these changes
더티 체킹 잘 적용되도록 하셨군요 추후에 쿼리 최적화를 하면 더 좋을거 같습니다 ㅎㅎ 수고하셨어용~~!

2024-07-19 16:49 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +        List<Stroke> beforeStrokes = memory.getStrokes();
7번은 쿼리가 너무 많이 나가서 fetch join으로 줄일 필요가 있어 보이긴 합니다..! Stroke 기준으로 Memory를 fetch join하고 해당 Memory에 Member를 fetch join하면 쿼리 2방은 줄일 수 있어 보여요~

2024-07-19 16:49 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +        List<Stroke> beforeStrokes = memory.getStrokes();
일단 넘겨둬도 큰 문제가 되진 않을거 같은데 시간 남을때 개선하면 좋을거 같아요~
아 그리고 image_entity랑 memory_detail_entity는 어디서 조회되는 걸까요? StrokeService가 아니라 MemoryService의 update에서 나가는거겠죠?

2024-07-19 16:49 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
>              beforeStrokes.forEach(stroke -> strokeRepository.deleteById(stroke.getId()));
이 부분도 각 엔티티마다 따로 delete를 하면 쿼리가 N개가 나가게 됩니다! 많아질수록 성능 이슈가 있는거죠
그래서 `deleteAllInBatch()`라는 메소드를 이용해서 한번에 삭제하고 JPA 1차 캐시를 비우게 하면 더 빠른 성능을 기대할 수 있을거 같습니다~

2024-07-19 17:12 UTC, merged

2024-07-22 04:57 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
> +        List<Stroke> beforeStrokes = memory.getStrokes();
이제 보았네용 요거 개선 알아보겠습니다!!
image_entity는 MemoryEntity를 조회할 때 image list 역참조 때 조회로만 발생합니다!
이미지 업데이트는 API가 분리되어 있어요
memory_detail_entity는 memory service 내부에서 업데이트 해주고 있습니다

2024-07-22 04:58 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/service/StrokeServiceImpl.java
>              beforeStrokes.forEach(stroke -> strokeRepository.deleteById(stroke.getId()));
그렇군요 !! 이것도 기억해서 적용해 두겠습니다 감사합니다 :))