feat: 타임라인 날짜 선택 후 위아래 무한 스크롤 기능 구현
depromeet/15th-team2-BE pull request #80
Opened 2024-07-22 03:42 UTC by penrose15

## 🌱 관련 이슈

- close #79 

## 📌 작업 내용 및 특이사항

- 타임라인 조회 api에서 날짜 선택 후 위/아래 스크롤 기능 구현
  - `GET : /api/memory/timeline`
```
request
GET : /api/memory/timeline-calendar?cursorId={cursorId}&cursorRecordAt={cursorRecordAt}&date={date}&showNewer={showNewer}&size={size}

cursorId : 최초 조회 이후 나온 timeline 리스트 중 가장 마지막 요소의 memory PK(nullable)
cursorRecordAt : 최초 조회 이후 나온 timeline 리스트 중 가장 마지막 요소의 memory recordAt(nullable)
date: 조회하고 싶은 날짜, yyyy-MM-dd(nullable)
showNewer : 조회하고 싶은 날짜 조회 이후, 날짜 기준 이전 정보를 보고 싶다면 false, 이후 정보를 보고 싶다면 true (nullable, default : false)
size : pageSize (not null)
```
  - 만약 최신순 조회 시 size 만 작성하면 됨
    - 최신순 조회 이후, 데이터 더 가져오려면 최신순 조회에서 가져온 리스트 중 가장 마지막 요소의 memoryId를 cursorId, recordAt를 cursorRecordAt로 작성해야 함
  - 날짜 기준 조회 시 date, size 입력
    - 날짜 기준 조회 이후, 이전 데이터 가져오고 싶다면 날짜 기준 조회시 나온 리스트의 가장 마지막 요소의 memoryPK(cursorId), recordAt(cursorRecordAt) 입력
    - 날짜 기준 조회 이후, 이후 데이터 가져오고 싶다면 날짜 기준 조회시 나온 리스트의 가장 첫번째 요소의 memoryPK(cursorId), recordAt(cursorRecordAt) 입력, showNewer = true

```
Response
{
  "status": 200,
  "code": "MEMORY_4",
  "message": "타임라인 조회에 성공하였습니다",
  "data": {
    "content": [
      {
        "memoryId": 6,
        "recordAt": "2024-07-16",
        "startTime": "11:00",
        "endTime": "11:50",
        "lane": 25,
        "diary": "나는 짱이야!! 내가 정말 멋져!!",
        "totalMeter": 150,
        "memoryDetailId": 6,
        "item": "오리발",
        "heartRate": 129,
        "pace": "05:00",
        "kcal": 300,
        "strokes": [
          {
            "strokeId": 6,
            "name": "자유형",
            "laps": 3,
            "meter": 150
          }
        ],
        "images": []
      },
      {
        "memoryId": 5,
        "recordAt": "2024-07-15",
        "startTime": "11:00",
        "endTime": "11:50",
        "lane": 25,
        "diary": "나는 짱이야!! 내가 정말 멋져!!",
        "totalMeter": 150,
        "memoryDetailId": 5,
        "item": "오리발",
        "heartRate": 129,
        "pace": "05:00",
        "kcal": 300,
        "strokes": [
          {
            "strokeId": 5,
            "name": "자유형",
            "laps": 3,
            "meter": 150
          }
        ],
        "images": []
      }
    ],
    "pageNumber": 0,
    "pageSize": 2,
    "hasNext": true
  }
}
```

## 📝 참고사항
-

2024-07-22 07:08 UTC, its-sky requested changes
수고하셨습니다~

2024-07-22 07:08 UTC, its-sky commented on module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
> +        System.out.println(resultRecordAtList);
출력문 삭제 부탁드립니다

2024-07-22 07:08 UTC, its-sky commented on module-infrastructure/persistence-database/src/test/java/com/depromeet/memory/repository/MemoryRepositoryTest.java
> +        System.out.println(resultRecordAtList);
출력문 삭제 부탁드립니다

2024-07-22 07:28 UTC, ywonchae1 reviewed
수고하셨어요 ~!!

2024-07-22 07:28 UTC, ywonchae1 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/member/entity/MemberEntity.java
>      }
이 메서드가 꼭 필요한 이유가 궁금합니다
member.getRefreshToken의 결과를 그대로 보여주면 값이 있거나 null이 되는 거 아닌가요?

2024-07-22 07:28 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +                    String cursorRecordAt,
String이 아니라 LocalDate 사용해야 하지 않을까요??

2024-07-22 07:28 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +                    String date,
String이 아니라 LocalDate 사용해야 하지 않을까요??

2024-07-22 07:28 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
> +            @RequestParam(value = "date", required = false) String date,
String이 아니라 LocalDate 사용해야 하지 않을까요??

2024-07-22 07:28 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +    ApiResponse<?> timelineCalendar(
RequestParam DTO 사용하는 게 더 좋아 보입니다!

2024-07-22 07:28 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
> +            int size) {
DTO 전달하는 게 더 좋아 보입니다!

2024-07-22 10:13 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +    ApiResponse<?> timelineCalendar(
근데 요건 Get 요청에 복잡한 쿼리 요청이라 RequestParam을 쓰는게 더 적절하지 않을까라고 생각합니다.

2024-07-22 12:37 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +                    String cursorRecordAt,
이제 년-월 로 받기 때문에 String으로 받아야 한다고 생각합니다.

2024-07-22 12:38 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +    ApiResponse<?> timelineCalendar(
get 요청이라 DTO로 Body를 보내기 보단 requestParam이 낫다고 생각합니다.

2024-07-22 12:38 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +                    String cursorRecordAt,
그럼 YearMonth도 있어요!

2024-07-22 12:39 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/facade/MemoryFacade.java
> +            int size) {
위와 같은 이유로 DTO를 사용하지 않고 정보를 받는데 굳이 DTO를 만들어서 사용하는건 불필요하다고 생각합니다.

2024-07-22 12:40 UTC, ywonchae1 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +    ApiResponse<?> timelineCalendar(
RequestParam DTO를 만드는 것도 되지 않나요??
null인 경우는 DTO 내부에서 처리하구요!
[참고](https://e-room.tistory.com/169)

2024-07-22 12:57 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryController.java
> +            @RequestParam(value = "date", required = false) String date,
변경해보겠습니다

2024-07-22 13:14 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/api/MemoryApi.java
> +                    String date,
변경해보겠습니다

2024-07-23 01:37 UTC, penrose15 commented on module-infrastructure/persistence-database/src/main/java/com/depromeet/memory/entity/MemoryEntity.java
> +    public static MemoryEntity create(Memory memory) {
refreshToken 만들다가 만든거 같은데 실수로 안지웠네요 지우겠습니다

2024-07-23 05:24 UTC, its-sky approved these changes
수고하셨습니다~

2024-07-23 05:24 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/service/TimelineServiceImpl.java
> +        log.info("localDate : {}", date);
이거 삭제 부탁드려요~

2024-07-23 05:24 UTC, its-sky commented on module-presentation/src/main/java/com/depromeet/memory/dto/request/TimelineRequestDto.java
> +    private LocalDate cursorRecordAt;
이건 뭔가요?? 날짜도 포함되어 있네요

2024-07-23 05:41 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/dto/request/TimelineRequestDto.java
> +    private LocalDate cursorRecordAt;
카톡에 적어놨지만 다시 말씀드리면

cursor의 기준으로 recordAt와 memoryPK로 두가지 기준을 사용했기 때문에 지우지 않았습니다. 

타임라인 무한 스크롤의 경우 최신순(등록날짜 내림차순)으로 정렬이 되어야 하는데 당시에는 과거의 날짜로 기록을 작성하는 경우가 발생하는 경우까지 고려하여 memoryPK만 cursor로 사용하는 경우 최신순으로 정렬이 되지 않을것이라고 판단되었습니다. 그래서 recordAt(등록날짜, cursorRecordAt) 를 추가적으로 요청받는 방식으로 설계하였습니다. (memoryPK또한 cursor로 활용한 이유는 하루에 여러번 수영기록을 작성하는 사람이 있을 경우 cursor의 unique가 보장되지 않아 같이 사용함)

현재 아직 슬랙에는 위에 대한 답변이 없어 수정을 보류하고 있습니다.

2024-07-23 05:42 UTC, penrose15 commented on module-presentation/src/main/java/com/depromeet/memory/service/TimelineServiceImpl.java
> +        log.info("localDate : {}", date);
다음 PR(#84)에 수정하도록 하겠습니다

2024-07-23 06:50 UTC, merged